# Generated by Django 5.0.4 on 2024-04-19 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_banner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='ativo',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='banner',
            old_name='imagem',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='banner',
            old_name='link_destino',
            new_name='url',
        ),
    ]
