# Generated by Django 5.0.4 on 2024-05-24 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_itemstock_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='type',
            name='slug',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
